### PR TITLE
Switch integration tests to Azure federated auth

### PR DESCRIPTION
**Pull request by troyready**

### CODE REVIEW

**Comment by troyready** [comment]
Blocked on either https://github.com/Azure/login/issues/188 or https://github.com/hashicorp/go-azure-helpers/issues/91

**Comment by rhyspaterson** [comment]
Did your workaround attemps in e436e14 or 5f23814 succeed until such time as support is implemented upstream? Have the same problem. Edit: Ah yep, I see the failed action. Damn.

**Comment by troyready** [comment]
@rhyspaterson no, sorry, it didn't end up working out. My suspicion is that it'd need a custom build of the provider now to make it work (until someone gets the proper support merged upstream)

**Comment by troyready** [comment]
Completed in #41

**Pull request closed without merging**
